### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by niyasc** [niyasc/stickit#1]
- [x] Implement menu in *right* way (refer gist copied from scratch)
- [x] Add colors in menu
- [x] Add delete note button
- [x] Add option to close all notes together in menu
- [ ] Add icons (refer scratch source code)
- [ ] Add about option and implement about dialog
- [x] Save & Load state from file
- ~~[ ] Add option to open hidden notes from menu~~

Planned application menu
--
 - Load notes
   - note 1 (first few words from note)
   - note 2
   - note 3
- Change color
   - green
   - blue
   - yellow
   - orange
- splitter
- close all notes
- splitter
- about
